

<MyPlashScreen>:
#    MDProgressBar:
#        id: id_pb1
#        value: 0
#        size_hint: .8, None
#        pos_hint: {"center_x": .5, "center_y": .4}
#        type: "indeterminate"
#        running_duration: .5
#        catching_duration: 2
    MDRaisedButton:
        text: "chargement"
        md_bg_color: 1, 0, 0, 1
        theme_text_color: "Custom"
        text_color: 1, 1, 1, 1